// IMPORTS
import '../styles/globals.css'
import 'react-toastify/dist/ReactToastify.css'
import Head                 from 'next/head'
import {useState}           from 'react'
import {
    ThemeProvider,
    createTheme,
    Paper,
}                           from '@mui/material'
import Navbar               from './components/navbar/Navbar'
import Footer               from './components/Footer'
import {ToastContainer}     from 'react-toastify'
import { SessionProvider }  from 'next-auth/react'
// END IMPORTS

// COMPONENT
function MyApp({ Component, pageProps: {session, ...pageProps} }) {

    const [isDark, setIsDark] = useState(false)
	
	const changeIsDark = e => {
		setIsDark(!isDark)
	}

    const theme = createTheme({
		palette: {
			mode: isDark ? 'dark' : 'light',
			primary: {
				main: isDark ? '#117e41' : '#006d40',

			},
			text: {
				primary: isDark ? '#cecece' : '#686868',
			},
        },
    })

    return (
    <>
        <Head>
            <title>KARU MAWIDA</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <SessionProvider session={session}>
            <ThemeProvider theme={theme}>
                <Paper>
                    <Navbar
                        themeMode={isDark}
                        changeTheme={changeIsDark}   
                    />
                    <ToastContainer/>
                    <Component 
                        {...pageProps} 
                        themeMode={isDark}
                        changeTheme={changeIsDark}    
                    />
                    <Footer
                        themeMode={isDark}
                        changeTheme={changeIsDark}   
                    />
                </Paper>
            </ThemeProvider>
        </SessionProvider>
    </>
    )
}
export default MyApp
// END COMPONENT