// IMPORTS
import '../styles/globals.css'
import styles       from '../styles/Home.module.css'
import Head         from 'next/head'
import {useState}   from 'react'
import {
    ThemeProvider,
    createTheme,
    Paper,
    Stack,
    Typography,
}                   from '@mui/material'
import Navbar       from './components/Navbar'
import Image        from 'next/image'
// END IMPORTS

// COMPONENT
function MyApp({ Component, pageProps }) {

    const [isDark, setIsDark] = useState(false)
	
	const changeIsDark = e => {
		setIsDark(!isDark)
	}

    const theme = createTheme({
		palette: {
			mode: isDark ? 'dark' : 'light',
			primary: {
				main: isDark ? '#117e41' : '#006d40',
			},
			text: {
				primary: isDark ? '#cecece' : '#686868',
			},
        },
    })

    return (
    <>
        <Head>
            <title>KARU MAWIDA</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <ThemeProvider theme={theme}>
            <Paper>
                <Navbar
                    themeMode={isDark}
                    changeTheme={changeIsDark}   
                />
                <Component 
                    {...pageProps} 
                    themeMode={isDark}
                    changeTheme={changeIsDark}    
                />
                <footer className={styles.footer}>
                    <Stack 
                        direction="row"
                        justifyContent="space-between"
                        alignItems="flex-start"
                        className={styles.footerlogo} 
                        sx={{margin:'15px 0'}}
                    >
                        <Image src="/images/karuLogo.png" alt="Karu Logo" width={80} height={80} />
                        {
                            isDark ?
                            <Image src='/images/nombrelogoclaro.png' alt='Nombre' width={140} height={30}/>
                            :
                            <Image src='/images/nombrelogo.png' alt='Nombre' width={140} height={30}/>
                        }
                        <Typography variant='body2'>
                            Powered by 
                            <Stack sx={{fontWeight:'bold'}}>
                                IBCode
                            </Stack>
                        </Typography>
                    </Stack>
                </footer>
            </Paper>
        </ThemeProvider>
    </>
    )
}
export default MyApp
// END COMPONENT